{% set name = "benten" %}
{% set version = "2021.1.5" %}
{% set sha256 = "31b1c633cdc1270814e134cd1e34e4320ebabe918edb231e916712ec345bc34e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rabix/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - benten-ls=benten.__main__:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - cwlformat
    - ruamel.yaml >=0.15.77
    - dukpy >=0.2.2

test:
  imports:
    - benten
  commands:
    - benten-ls --help

about:
  home: https://github.com/rabix/benten
  license: Apache-2.0
  license_file: LICENSE
  summary: A language server for Common Workflow Language documents.
  description: |
    benten implements the language server protocol to allow editors like VSCode to provide
    syntax highlighting, autocomplete and other features for editing CWL (Common Workflow Language)
    documents
  doc_url: https://github.com/rabix/benten
  dev_url: https://github.com/rabix/benten

extra:
  recipe-maintainers:
    - pvanheus
