{% set name = "benten" %}
{% set version = "2020.06.03.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rabix/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 5cd981c13c991e704af7304899d32406a38c09d69f7f624ce3bebd5541025a07

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - benten-ls=benten.__main__:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - dukpy
    - ruamel.yaml

test:
  imports:
    - benten
  commands:
    - benten-ls -h

about:
  home: https://github.com/rabix/benten
  license: Apache-2.0
  license_file: LICENSE
  summary: A language server for Common Workflow Language documents.
  description: |
    benten implements the language server protocol to allow editors like VSCode to provide
    syntax highlighting, autocomplete and other features for editing CWL (Common Workflow Language)
    documents
  doc_url: https://github.com/rabix/benten
  dev_url: https://github.com/rabix/benten

extra:
  recipe-maintainers:
    - pvanheus
