travis:
  secure:
    BINSTAR_TOKEN: egmpEkkBoloWjdYEYHSO5djz1/Wp3H6NcgkxqlGq9G0dGgZymGgpByWtQYHwLnuuNvJH2+VFsbq/zFcuyqyxYUqtREo46Pv1XL7PvMqV/KZXCDaXMMwILtmoCln3OrvSv/S198gBFcLhyPCIWjhkrRIk+65EC5h2eo+pvmY/0o6WrpsTk6xvql8tntG/UoY9EvAoivXTAfxP6E/Oo7TeBnUHj/ZQ2gKTxYhJP67KnutdAWve3uy+XtlG05BZlB+ONrwBh87cd4/NGzs9yvNkaWe/Nln1SH/7zmEZQifUEZpkkYSzS6yQmwN9JNiyXmTaxWzNSANwj4VazjpB1cyT19T5/4dHo93ObYD7N029wg5pt0nffQ9iDpHpUXFVm7Au4CCMvt3f/8W+aTMJRq7AWYm3TRTIovJl07FL+fpDeXSWSJmirNI7yEDb+U55Kk3lC2PD+vhLKLxw22PQrKbR7XEKdErO3mBmuCrpZgoxgagpHSCemTJiGxhF41ImrSlTdp3Ef8pvO8PuMvOcMUbbrUCKUffuFq7R/rlql6MMP0R3Of/XIKDWqWw+7qqMmly0d7Ea+P0VOK+bbLZGC5AxX2j4rzelW0oWhjeBfP9n/7QDly3ThqmreFuY+lfw5rieKFot/lbj46wEdRBAvAnyqSpYWgeLkoG54mxGbGdjISU=
conda_forge_output_validation: true
bot:
  automerge: true
